// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MNKR_TimerEX","status":true,"description":"タイマーをカウントアップ・ダウン、表示・非表示を切り替えできるようにします。","parameters":{"countUpSwitch":"25","hideSwitch":"27","countStopValue":"9"}}
];
